<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="AutomtionTest" duration-ms="63862" started-at="2020-12-03T10:45:03Z" finished-at="2020-12-03T10:46:07Z">
    <groups>
    </groups>
    <test name="WebTest" duration-ms="63862" started-at="2020-12-03T10:45:03Z" finished-at="2020-12-03T10:46:07Z">
      <class name="autotest.suites.steps.project.ProjectTest">
        <test-method status="PASS" signature="StartSession()[pri:0, instance:autotest.suites.steps.project.ProjectTest@327471b5]" name="StartSession" is-config="true" duration-ms="6636" started-at="2020-12-03T17:44:56Z" finished-at="2020-12-03T17:45:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StartSession -->
        <test-method status="PASS" signature="createNewProject()[pri:1, instance:autotest.suites.steps.project.ProjectTest@327471b5]" name="createNewProject" duration-ms="31334" started-at="2020-12-03T17:45:03Z" finished-at="2020-12-03T17:45:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewProject -->
        <test-method status="PASS" signature="createTask()[pri:2, instance:autotest.suites.steps.project.ProjectTest@327471b5]" name="createTask" duration-ms="16968" started-at="2020-12-03T17:45:34Z" finished-at="2020-12-03T17:45:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createTask -->
        <test-method status="FAIL" signature="ReopenTask()[pri:3, instance:autotest.suites.steps.project.ProjectTest@327471b5]" name="ReopenTask" duration-ms="15540" started-at="2020-12-03T17:45:51Z" finished-at="2020-12-03T17:46:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Task TaskNameFFRmx not appear in the screen expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Task TaskNameFFRmx not appear in the screen expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at autotest.suites.steps.project.ProjectTest.verifyReopenedTask(ProjectTest.java:166)
	at autotest.suites.steps.project.ProjectTest.ReopenTask(ProjectTest.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReopenTask -->
        <test-method status="PASS" signature="Dispose()[pri:0, instance:autotest.suites.steps.project.ProjectTest@327471b5]" name="Dispose" is-config="true" duration-ms="1169" started-at="2020-12-03T17:46:07Z" finished-at="2020-12-03T17:46:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Dispose -->
      </class> <!-- autotest.suites.steps.project.ProjectTest -->
    </test> <!-- WebTest -->
  </suite> <!-- AutomtionTest -->
</testng-results>
